### PR TITLE
docs: Add ADR template

### PR DESCRIPTION
**Pull request by UlisesGascon**
closes https://github.com/expressjs/discussions/issues/285

Note: this template was used in #290 and #289

### CODE REVIEW

**Review by blakeembrey — APPROVED** [review]

**Review by mertcanaltin — APPROVED** [review]
LGTM

**Review by bjohansebas — APPROVED** [review]
Maybe it could also be added as a PR template.

**Comment by carpasse** [comment]
I would stick to the [original template](https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions)

Just because we can easily leverage the ADR generation using one of the available cli tools available on [npm](https://www.npmjs.com/search?q=adr)

**Comment by UlisesGascon** [comment]
As agreed on the last TC meeting I am merging the PR. @bjohansebas can you create the PR template?

**Pull request merged**
